// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ZrzenIIKiWpMMdVj-EBMy6czQrEmTd0',
    appId: '1:1093394564352:web:080339e9c9d4b5568ddfe5',
    messagingSenderId: '1093394564352',
    projectId: 'indehlize',
    authDomain: 'indehlize.firebaseapp.com',
    storageBucket: 'indehlize.appspot.com',
    measurementId: 'G-DX0T6HS090',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4okR9arqFFgVHiRnK8YPPyiKJIZIK240',
    appId: '1:1093394564352:android:f042b2313b1e6d0b8ddfe5',
    messagingSenderId: '1093394564352',
    projectId: 'indehlize',
    storageBucket: 'indehlize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5RbKBMK7hYJ_GNnwauiEV4ryrEhfQJ4s',
    appId: '1:1093394564352:ios:c48852d462caae058ddfe5',
    messagingSenderId: '1093394564352',
    projectId: 'indehlize',
    storageBucket: 'indehlize.appspot.com',
    iosClientId: '1093394564352-seike4e0b4cg9g9mregs9cjnt8ckvc2b.apps.googleusercontent.com',
    iosBundleId: 'com.aaostudios.indehlize',
  );
}
